version: "3"
services:
  machine-server:
    hostname: machine-server
    image: machine:latest
    environment:
      - ASPNETCORE_Kestrel__Endpoints__Https__Url=http://*:8087
      - ASPNETCORE_ConnectionStrings__Hangfire=mongodb://mongo:27017/machine_jobs
      - ASPNETCORE_ConnectionStrings__Mongo=mongodb://mongo:27017/machine
      - ASPNETCORE_Logging__LogLevel__Default=Information
      - ASPNETCORE_Logging__LogLevel__Microsoft.AspNetCore=Warning
      - ASPNETCORE_Auth__Domain=sil-appbuilder.auth0.com
      - ASPNETCORE_Auth__Audience=https://machine.sil.org
    expose:
      - 8087
    ports:
      - 8087:8087
    depends_on:
      - mongo
    volumes:
      - "/var/lib/engine_server:/var/lib/machine"
    entrypoint:
      [
        'dotnet',
        '/app/engine_server/SIL.Machine.Serval.EngineServer.dll'
      ]
  machine-job-server:
    hostname: machine-job-server
    image: machine:latest
    environment:
      - ASPNETCORE_ConnectionStrings__Hangfire=mongodb://mongo:27017/machine_jobs
      - ASPNETCORE_ConnectionStrings__Mongo=mongodb://mongo:27017/machine
      - ASPNETCORE_ConnectionStrings__Serval=http://serval
      - ASPNETCORE_Logging__LogLevel__Default=Information
      - ASPNETCORE_Logging__LogLevel__Microsoft.AspNetCore=Warning
      - ASPNETCORE_Kestrel__Endpoints__Http__Url=http://*:80
      - ASPNETCORE_Kestrel__EndpointDefaults__Protocols=Http2
      - ASPNETCORE_Kestrel__TranslationEngines__0=SmtTransfer
    depends_on:
      - mongo
    volumes:
      - "/var/lib/job_server:/var/lib/machine"
    entrypoint:
      [
        'dotnet',
        '/app/job_server/SIL.Machine.Serval.JobServer.dll'
      ]
  mongo:
    hostname: mongo
    container_name: mongo
    image: mongo:4.2-bionic
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "/usr/local/mongo-volume:/data/db"
    entrypoint: [ '/usr/bin/mongod', '--bind_ip', '0.0.0.0' ]
