version: "{build}"
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - master
skip_branch_with_pr: true
image: Visual Studio 2019
configuration: Release
nuget:
  disable_publish_on_pr: true
before_build:
  - ps: nuget restore Machine.sln
build:
  project: Machine.sln
  verbosity: minimal
test_script:
  - ps: |
      $failed = $FALSE
      dotnet test --no-build -c Release --test-adapter-path:. --logger:Appveyor tests\SIL.Machine.Tests\SIL.Machine.Tests.csproj
      if (-not $?) { $failed = $TRUE }
      dotnet test --no-build -c Release --test-adapter-path:. --logger:Appveyor tests\SIL.Machine.Morphology.HermitCrab.Tests\SIL.Machine.Morphology.HermitCrab.Tests.csproj
      if (-not $?) { $failed = $TRUE }
      dotnet test --no-build -c Release --test-adapter-path:. --logger:Appveyor tests\SIL.Machine.Translation.Thot.Tests\SIL.Machine.Translation.Thot.Tests.csproj
      if (-not $?) { $failed = $TRUE }
      dotnet test --no-build -c Release --test-adapter-path:. --logger:Appveyor tests\SIL.Machine.WebApi.Tests\SIL.Machine.WebApi.Tests.csproj
      if (-not $?) { $failed = $TRUE }
      if ($failed) { throw "The unit tests failed." }
deploy_script:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -eq "true")
      {
          dotnet pack src\SIL.Machine\SIL.Machine.csproj -c Release -o artifacts
          dotnet pack src\SIL.Machine.Translation.Thot\SIL.Machine.Translation.Thot.csproj -c Release -o artifacts
          dotnet pack src\SIL.Machine.WebApi\SIL.Machine.WebApi.csproj -c Release -o artifacts
          dotnet pack src\SIL.Machine.Morphology.HermitCrab\SIL.Machine.Morphology.HermitCrab.csproj -c Release -o artifacts
          dotnet pack src\SIL.Machine.Translator\SIL.Machine.Translator.csproj -c Release -o artifacts
          dotnet pack src\SIL.Machine.HCParser\SIL.Machine.HCParser.csproj -c Release -o artifacts
          dotnet pack src\SIL.Machine.Plugin\SIL.Machine.Plugin.csproj -c Release -o artifacts
          dotnet nuget push artifacts\*.nupkg -n true -k $env:NUGET_API_KEY -s https://api.nuget.org/v3/index.json
      }
