apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: machine-job-server
  name: machine-job-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: machine-job-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: machine-job-server
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - command:
            - dotnet
            - /app/job_server/SIL.Machine.WebApi.JobServer.dll
          workingDir: /app/job_server
          env:
            - name: ASPNETCORE_ConnectionStrings__Hangfire
              value: mongodb://mongo:27017/machine_jobs
            - name: ASPNETCORE_ConnectionStrings__Mongo
              value: mongodb://mongo:27017/machine
            - name: ASPNETCORE_SharedFile_Uri
              value: s3://aqua-ml-data/
            - name: ASPNETCORE_Logging__LogLevel__Default
              value: Information
            - name: ASPNETCORE_Logging__LogLevel__Microsoft.AspNetCore
              value: Warning
          image: ghcr.io/sillsdev/machine:latest
          imagePullPolicy: "Always"
          name: machine-job-server
          resources:
            limits:
              memory: "1000Mi"
              cpu: "1.5"
            requests:
              memory: "100Mi"
              cpu: "100m"
          volumeMounts:
            - mountPath: /var/lib/machine/engines
              name: machine-job-server-engines
            - mountPath: /var/lib/machine/corpora
              name: machine-job-server-data
      hostname: machine-job-server
      restartPolicy: Always
      {{- if .Values.localVolume }}
      volumes:
        - hostPath:
            path: /host/engines #/host should be mounted from C:\usr\local
          name: machine-job-server-engines
        - hostPath:
            path: /host/corpora
          name: machine-job-server-data
      {{- else}}
      volumes:
        - name: machine-job-server-engines
          persistentVolumeClaim:
            claimName: machine-engines-claim
        - name: machine-job-server-data
          persistentVolumeClaim:
            claimName: machine-corpora-claim
      {{- end}}
status: {}
