apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\johnm\Documents\repos\machine\docker\development\kompose.exe convert -c --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: machine-job-server
  name: machine-job-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: machine-job-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\johnm\Documents\repos\machine\docker\development\kompose.exe convert -c --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: machine-job-server
    spec:
      containers:
        - command:
            - dotnet
            - /app/SIL.Machine.WebApi.JobServer.dll
          env:
            - name: ASPNETCORE_ConnectionStrings__Hangfire
              value: mongodb://mongo:27017/machine_jobs
            - name: ASPNETCORE_ConnectionStrings__Mongo
              value: mongodb://mongo:27017/machine
            - name: ASPNETCORE_Logging__LogLevel__Default
              value: Information
            - name: ASPNETCORE_Logging__LogLevel__Microsoft.AspNetCore
              value: Warning
          image: ghcr.io/sillsdev/machine:latest
          name: machine-job-server
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/machine/engines
              name: machine-job-server-hostpath0
            - mountPath: /var/lib/machine/data
              name: machine-job-server-hostpath1
      hostname: machine-job-server
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /host/engines #/host should be mounted from C:\usr\local
          name: machine-job-server-hostpath0
        - hostPath:
            path: /host/data
          name: machine-job-server-hostpath1
status: {}
