apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\johnm\Documents\repos\machine\docker\development\kompose.exe convert -c --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: machine-server
  name: machine-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: machine-server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\johnm\Documents\repos\machine\docker\development\kompose.exe convert -c --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: machine-server
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - command:
            - dotnet
            - /app/SIL.Machine.WebApi.ApiServer.dll
          env:
            - name: ASPNETCORE_Auth__Audience
              value: https://machine.sil.org
            - name: ASPNETCORE_Auth__Domain
              value: sil-appbuilder.auth0.com
            - name: ASPNETCORE_ConnectionStrings__Hangfire
              value: mongodb://mongo:27017/machine_jobs
            - name: ASPNETCORE_ConnectionStrings__Mongo
              value: mongodb://mongo:27017/machine
            - name: ASPNETCORE_Kestrel__Endpoints__Https__Url
              value: http://*
            - name: ASPNETCORE_Logging__LogLevel__Default
              value: Information
            - name: ASPNETCORE_Logging__LogLevel__Microsoft.AspNetCore
              value: Warning
          image: ghcr.io/sillsdev/machine:latest
          imagePullPolicy: "Always"
          name: machine-server
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "350Mi"
              cpu: "500m"
          volumeMounts:
            - mountPath: /var/lib/machine/engines
              name: machine-server-engines
            - mountPath: /var/lib/machine/data
              name: machine-server-data
            - mountPath: /root/.aspnet/DataProtection-Keys
              name: machine-server-keys
      hostname: machine-server
      restartPolicy: Always
      {{- if .Values.localVolume }}
      volumes:
        - hostPath:
            path: /host/engines #/host should be mounted from C:\usr\local
          name: machine-server-engines
        - hostPath:
            path: /host/data
          name: machine-server-data
        - hostPath:
            path: /host/DataProtection-Keys
          name: machine-server-keys
      {{- else}}
      volumes:
        - name: machine-server-engines
          persistentVolumeClaim:
            claimName: machine-engines-claim
        - name: machine-server-data
          persistentVolumeClaim:
            claimName: machine-data-claim
        - name: machine-server-keys
          persistentVolumeClaim:
            claimName: machine-keys-claim
      {{- end}}
status: {}
