apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: machine-ingress
spec:
  ingressClassName: nginx
  {{- if .Values.enableTls }}
  tls:
    - hosts:
        - {{.Values.externalHost}}
  #    secretName: testsecret-tls
  {{- end }}
  rules:
    - host: {{.Values.externalHost}}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: machine-server
                port:
                  number: 80
