apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\johnm\Documents\repos\machine\docker\development\kompose.exe convert -c --volumes hostPath
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongo
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\johnm\Documents\repos\machine\docker\development\kompose.exe convert -c --volumes hostPath
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: mongo
    spec:
      containers:
        - command:
            - /usr/bin/mongod
            - --bind_ip
            - 0.0.0.0
          image: mongo:4.2-bionic
          name: mongo
          ports:
            - containerPort: 27017
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: mongo-hostpath0
      hostname: mongo
      restartPolicy: Always
      volumes:
        - hostPath:
            path: /data/mongodb #this is mounted in the minikube persistent storage of /data: https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/
          name: mongo-hostpath0
status: {}
